### ISSUE TITLE
Подключить роутер и настроить табы в админ панели.

### ISSUE THREAD

**Issue by Gyxer513** [LiteraExcurs/admin-panel#3]
Админку реализуем в виде SPA, нужно подключить роутер и настроить табы.

**Comment by anastasia-bazaeva** [comment]
@Gyxer513 Есть ли пример что это за вид? Я не участвовала в обсуждении, что такое SAP и табы?

**Comment by Gyxer513** [comment]
@anastasia-bazaeva Извини, я ошибся в названии. Реализуем single page application. Еще раз посмотрел доку и не вижу смысла делать табы в хедере, сделаем как в доке боковой минюшкой. 

![Image](https://github.com/LiteraExcurs/admin-panel/assets/102280477/e7ee6e31-fd02-41d0-a81e-f8b58d9628fa)
